import {useEffect,useState} from 'react';
import {Activity,BarChart3,BookOpen,Search,ShieldCheck,TrendingUp} from 'lucide-react';
type Signal={ticker:string;label:string;confidence:number;price:number;entry_low:number;entry_high:number;stop:number;target:number;rationale:string;warnings?:string[];error?:string};
type Perf={closed_trades:number;win_rate:number;realized_pnl:number;profit_factor:number|null};
const API_BASE=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'');
export default function App(){
 const [symbols,setSymbols]=useState('AAPL, MSFT, NVDA, AMZN, META'),[signals,setSignals]=useState<Signal[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [perf,setPerf]=useState<Perf>({closed_trades:0,win_rate:0,realized_pnl:0,profit_factor:null});
 useEffect(()=>{fetch(`${API_BASE}/api/v1/performance`).then(r=>r.json()).then(setPerf).catch(()=>{})},[]);
 async function scan(){setLoading(true);setError('');try{const tickers=symbols.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);const r=await fetch(`${API_BASE}/api/v1/scan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tickers,earnings_dates:{}})});if(!r.ok)throw new Error((await r.json()).detail);setSignals((await r.json()).results)}catch(e){setError(e instanceof Error?e.message:'Scan failed')}finally{setLoading(false)}}
 async function paper(s:Signal){const quantity=Math.max(1,Math.floor(500/(s.price-s.stop)));const r=await fetch(`${API_BASE}/api/v1/positions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticker:s.ticker,entry:s.price,quantity,stop:s.stop,target:s.target})});if(!r.ok){setError((await r.json()).detail);return}setError(`${s.ticker} added to paper portfolio — ${quantity} shares`)}
 return <main><aside><div className="brand"><Activity/> StockPilot <b>AI</b></div><nav><span className="active"><BarChart3/> Overview</span><span><TrendingUp/> Signals</span><span><BookOpen/> Journal</span></nav><div className="safe"><ShieldCheck/><div><b>Paper mode</b><small>No broker orders</small></div></div></aside><section><header><div><p className="eyebrow">TRADING COMMAND CENTER</p><h1>Good morning, Nari.</h1><p>Scan selectively. Record every decision.</p></div><div className="status">● V2 ENGINE READY</div></header><div className="cards"><article><small>VALIDATED WIN RATE</small><strong>60.0%</strong><em>Historical validation</em></article><article><small>PAPER WIN RATE</small><strong>{perf.win_rate}%</strong><em>{perf.closed_trades} closed trades</em></article><article><small>REALIZED P&amp;L</small><strong>${perf.realized_pnl}</strong><em>Paper only</em></article><article><small>PROFIT FACTOR</small><strong>{perf.profit_factor??'—'}</strong><em>Goal ≥ 1.30</em></article></div><div className="panel"><p className="eyebrow">WATCHLIST SCANNER</p><h2>Scan up to 25 liquid US stocks</h2><div className="search"><Search/><input value={symbols} onChange={e=>setSymbols(e.target.value)} onKeyDown={e=>e.key==='Enter'&&scan()}/><button onClick={scan} disabled={loading}>{loading?'Scanning…':'Run scan'}</button></div>{error&&<p className={error.includes('added')?'success':'error'}>{error}</p>}{signals.length>0&&<div className="signal-table"><div className="tr head"><span>Ticker</span><span>Signal</span><span>Score</span><span>Entry / Stop / Target</span><span>Safety</span><span></span></div>{signals.map(s=><div className="tr" key={s.ticker}><b>{s.ticker}</b>{s.error?<span className="error">Data error</span>:<><span className={`badge ${s.label.replace(' ','').toLowerCase()}`}>{s.label}</span><span>{s.confidence}%</span><span>${s.entry_low}–${s.entry_high}<small>${s.stop} / ${s.target}</small></span><span>{s.warnings?.length?s.warnings.join(', '):'All gates passed'}</span><button onClick={()=>paper(s)} disabled={s.label!=='STRONG BUY'}>Paper trade</button></>}</div>)}</div>}</div><div className="note"><ShieldCheck/><div><b>Safety gates are enforced</b><p>Maximum five open positions. Strong Buy requires every trend, momentum, liquidity, gap, and earnings rule to pass.</p></div></div></section></main>
}
