import {useEffect,useState} from 'react';
import {Activity,BarChart3,BookOpen,Search,ShieldCheck,TrendingUp} from 'lucide-react';

type Screen='overview'|'signals'|'journal';
type Signal={id?:number;ticker:string;label:string;confidence:number;price:number;entry_low:number;entry_high:number;stop:number;target:number;rationale:string;warnings?:string[];error?:string;created_at?:string};
type Position={id:number;ticker:string;entry:number;quantity:number;stop:number;target:number;exit_price:number|null;status:string;opened_at:string;closed_at:string|null};
type Perf={closed_trades:number;win_rate:number;realized_pnl:number;profit_factor:number|null};
type Universe={id:string;name:string;description:string;size:number};
const API_BASE=(import.meta.env.VITE_API_URL??'').replace(/\/$/,'');
const api=(path:string,options?:RequestInit)=>fetch(`${API_BASE}${path}`,options);

export default function App(){
 const [screen,setScreen]=useState<Screen>('overview');
 const [symbols,setSymbols]=useState('AAPL, MSFT, NVDA, AMZN, META');
 const [signals,setSignals]=useState<Signal[]>([]),[journal,setJournal]=useState<Signal[]>([]),[positions,setPositions]=useState<Position[]>([]);
 const [universes,setUniverses]=useState<Universe[]>([]),[universe,setUniverse]=useState('mega_cap');
 const [loading,setLoading]=useState(false),[error,setError]=useState('');
 const [perf,setPerf]=useState<Perf>({closed_trades:0,win_rate:0,realized_pnl:0,profit_factor:null});
 const [closePrices,setClosePrices]=useState<Record<number,string>>({});
 useEffect(()=>{void refreshSummary();api('/api/v1/universes').then(r=>r.json()).then(setUniverses).catch(()=>{})},[]);
 useEffect(()=>{if(screen==='journal')void refreshJournal()},[screen]);
 async function refreshSummary(){api('/api/v1/performance').then(r=>r.json()).then(setPerf).catch(()=>{})}
 async function refreshJournal(){try{const [s,p]=await Promise.all([api('/api/v1/signals?limit=100'),api('/api/v1/positions')]);setJournal(await s.json());setPositions(await p.json())}catch{setError('Could not load journal data')}}
 async function manualScan(){const tickers=symbols.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);await run('/api/v1/scan',{tickers,earnings_dates:{}})}
 async function universeScan(){await run('/api/v1/scan/universe',{universe,top_n:10})}
 async function run(path:string,body:unknown){setLoading(true);setError('');try{const r=await api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).detail);setSignals((await r.json()).results);setScreen('signals')}catch(e){setError(e instanceof Error?e.message:'Scan failed')}finally{setLoading(false)}}
 async function paper(s:Signal){const quantity=Math.max(1,Math.floor(500/Math.max(.01,s.price-s.stop)));const r=await api('/api/v1/positions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticker:s.ticker,entry:s.price,quantity,stop:s.stop,target:s.target})});if(!r.ok){setError((await r.json()).detail);return}setError(`${s.ticker} added to paper portfolio — ${quantity} shares`)}
 async function closePosition(p:Position){const exit=Number(closePrices[p.id]);if(!exit||exit<=0){setError('Enter a valid exit price');return}const r=await api(`/api/v1/positions/${p.id}/close`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({exit_price:exit})});if(!r.ok){setError((await r.json()).detail);return}await refreshJournal();await refreshSummary();setError(`${p.ticker} paper position closed`)}
 return <main><aside><div className="brand"><Activity/> StockPilot <b>AI</b></div><nav><button className={screen==='overview'?'active':''} onClick={()=>setScreen('overview')}><BarChart3/> Overview</button><button className={screen==='signals'?'active':''} onClick={()=>setScreen('signals')}><TrendingUp/> Signals</button><button className={screen==='journal'?'active':''} onClick={()=>setScreen('journal')}><BookOpen/> Journal</button></nav><div className="safe"><ShieldCheck/><div><b>Paper mode</b><small>No broker orders</small></div></div></aside><section><header><div><p className="eyebrow">TRADING COMMAND CENTER</p><h1>{screen==='overview'?'Good morning, Nari.':screen==='signals'?'Ranked Signals':'Signal & Trade Journal'}</h1><p>{screen==='overview'?'Scan selectively. Record every decision.':screen==='signals'?'Only the highest-scoring setups from the selected universe.':'Review every signal and paper-trade outcome.'}</p></div><div className="status">● V2 ENGINE READY</div></header>{error&&<p className={error.includes('added')||error.includes('closed')?'success flash':'error flash'}>{error}</p>}{screen==='overview'&&<Overview perf={perf} universes={universes} universe={universe} setUniverse={setUniverse} symbols={symbols} setSymbols={setSymbols} loading={loading} universeScan={universeScan} manualScan={manualScan}/>} {screen==='signals'&&<SignalsTable signals={signals} loading={loading} onScan={()=>setScreen('overview')} paper={paper}/>} {screen==='journal'&&<Journal signals={journal} positions={positions} closePrices={closePrices} setClosePrices={setClosePrices} closePosition={closePosition}/>}</section></main>
}

function MetricCards({perf}:{perf:Perf}){return <div className="cards"><article><small>VALIDATED WIN RATE</small><strong>60.0%</strong><em>Historical validation</em></article><article><small>PAPER WIN RATE</small><strong>{perf.win_rate}%</strong><em>{perf.closed_trades} closed trades</em></article><article><small>REALIZED P&amp;L</small><strong>${perf.realized_pnl}</strong><em>Paper only</em></article><article><small>PROFIT FACTOR</small><strong>{perf.profit_factor??'—'}</strong><em>Goal ≥ 1.30</em></article></div>}
function Overview({perf,universes,universe,setUniverse,symbols,setSymbols,loading,universeScan,manualScan}:{perf:Perf;universes:Universe[];universe:string;setUniverse:(x:string)=>void;symbols:string;setSymbols:(x:string)=>void;loading:boolean;universeScan:()=>void;manualScan:()=>void}){const selected=universes.find(u=>u.id===universe);return <><MetricCards perf={perf}/><div className="panel"><p className="eyebrow">AUTOMATIC MARKET SCANNER</p><h2>Scan a category and show its top 10</h2><p className="muted">The engine ranks complete V2 setups first, then confidence. A Top 100 scan can take one or two minutes on the free server.</p><div className="auto-scan"><select value={universe} onChange={e=>setUniverse(e.target.value)}>{universes.map(u=><option value={u.id} key={u.id}>{u.name} ({u.size})</option>)}</select><button onClick={universeScan} disabled={loading}>{loading?'Scanning market…':'Scan & rank top 10'}</button></div>{selected&&<p className="universe-note">{selected.description}</p>}<div className="divider"><span>OR MANUAL TICKERS</span></div><div className="search"><Search/><input value={symbols} onChange={e=>setSymbols(e.target.value)} onKeyDown={e=>e.key==='Enter'&&manualScan()}/><button onClick={manualScan} disabled={loading}>{loading?'Scanning…':'Run scan'}</button></div></div><div className="note"><ShieldCheck/><div><b>Safety gates remain enforced</b><p>Strong Buy requires trend, momentum, liquidity, gap, and earnings rules to pass. Ranking does not bypass any rule.</p></div></div></>}
function SignalsTable({signals,loading,onScan,paper}:{signals:Signal[];loading:boolean;onScan:()=>void;paper:(s:Signal)=>void}){return <div className="panel page-panel"><div className="panel-title"><div><p className="eyebrow">TOP RESULTS</p><h2>{signals.length?`${signals.length} ranked opportunities`:'No scan results yet'}</h2></div><button className="secondary" onClick={onScan}>New scan</button></div>{loading&&<p className="muted">Scanning price history and applying safety gates…</p>}{!loading&&!signals.length&&<div className="empty"><TrendingUp/><b>Run a market or manual scan</b><span>The ten highest-ranked valid results will appear here.</span></div>}{signals.length>0&&<div className="signal-table"><div className="tr head"><span>Rank / Ticker</span><span>Signal</span><span>Score</span><span>Entry / Stop / Target</span><span>Reason</span><span></span></div>{signals.map((s,i)=><div className="tr" key={`${s.ticker}-${i}`}><b>#{i+1} {s.ticker}</b>{s.error?<span className="error">Data error</span>:<><span className={`badge ${s.label.replace(' ','').toLowerCase()}`}>{s.label}</span><span>{s.confidence}%</span><span>${s.entry_low}–${s.entry_high}<small>${s.stop} / ${s.target}</small></span><span title={s.rationale}>{s.warnings?.length?s.warnings.join(', '):s.rationale}</span><button onClick={()=>paper(s)} disabled={s.label!=='STRONG BUY'}>Paper trade</button></>}</div>)}</div>}</div>}
function Journal({signals,positions,closePrices,setClosePrices,closePosition}:{signals:Signal[];positions:Position[];closePrices:Record<number,string>;setClosePrices:(x:Record<number,string>)=>void;closePosition:(p:Position)=>void}){return <div className="journal-grid"><div className="panel page-panel"><p className="eyebrow">PAPER POSITIONS</p><h2>Open and closed trades</h2>{!positions.length?<div className="empty"><BookOpen/><b>No paper trades yet</b><span>Add a Strong Buy from Signals.</span></div>:<div className="simple-table"><div className="jr head"><span>Ticker</span><span>Entry</span><span>Stop / Target</span><span>Status / Exit</span></div>{positions.map(p=><div className="jr" key={p.id}><b>{p.ticker}<small>{p.quantity} shares</small></b><span>${p.entry}</span><span>${p.stop} / ${p.target}</span><span>{p.status==='OPEN'?<div className="close-box"><input placeholder="Exit price" value={closePrices[p.id]??''} onChange={e=>setClosePrices({...closePrices,[p.id]:e.target.value})}/><button onClick={()=>closePosition(p)}>Close</button></div>:<b className="closed">Closed @ ${p.exit_price}</b>}</span></div>)}</div>}</div><div className="panel page-panel"><p className="eyebrow">SIGNAL HISTORY</p><h2>Latest evaluations</h2>{!signals.length?<div className="empty"><Activity/><b>No saved signals</b></div>:<div className="simple-table"><div className="jr signal-head head"><span>Ticker</span><span>Signal</span><span>Score</span><span>Created</span></div>{signals.map(s=><div className="jr signal-head" key={s.id}><b>{s.ticker}</b><span className={`badge ${s.label.replace(' ','').toLowerCase()}`}>{s.label}</span><span>{s.confidence}%</span><span>{s.created_at?new Date(s.created_at).toLocaleString():'—'}</span></div>)}</div>}</div></div>}
